import matplotlib.pyplot as plt
import numpy as np
from PIL import Image
from datetime import datetime
import constants

def generatePriceChart(hours, prices, delta):
  plt.style.use('seaborn-dark')
  plt.plot(hours, prices, c='silver')

  for i in range(constants.NUM_PREVIOUS_PUPDATES):
    if i == constants.NUM_PREVIOUS_PUPDATES-1:
      plt.plot(hours[i], prices[i], marker='*', ms=15, c='gold' )
    else:
      pointStyle = 'g^' if (prices[i+1] >= prices[i]) else 'rv'
      plt.plot(hours[i], prices[i], pointStyle, markersize=6)

  plt.title("12-Hour Puppy Coin Price Summary")
  plt.xlabel("Time (EST)")
  plt.ylabel("Price per 1 million $PUP (USD before fees)")
  plt.xticks(hours)
  plt.grid()
  plt.figtext(0.99, 0.01, 'Generated by @PuppyCoinBot', fontsize=7, ha='right')
  deltaColour = 'g' if delta >= 0 else 'r'
  if (delta > 0):
    deltaColour = 'green'
    deltaPlusMinus = '+'
  elif (delta == 0):
    deltaColour = 'silver'
    deltaPlusMinus = '+'
  else:
    deltaColour = 'red'
    deltaPlusMinus = '-'
  delta = str('{0:.2f}'.format(delta))+'%'
  plt.figtext(0.87, 0.9, deltaPlusMinus+delta, fontsize=10, ha='center', color=deltaColour)
  currentTimeString = datetime.now().strftime("%m%d%Y_%H%M%S")
  filename = 'pricechart_'+currentTimeString
  filepath = './pricecharts/'+filename
  plt.savefig(filepath)
  return filepath+'.png'